FROM node:latest

RUN apt-get update && \
    apt-get install -yq --no-install-recommends libzmq3-dev jupyter python3-pip && \
    apt-get clean

RUN pip3 install -I \
    setuptools \
    wheel \
    jupyter

USER node

WORKDIR /home/node

COPY --chown=node:node . .

RUN rm -rf node_modules && npm install

CMD npm run test && node bin/ijsinstall.js
