FROM node:4

RUN apt-get update && \
    apt-get install -yq --no-install-recommends libzmq3-dev ipython-notebook && \
    apt-get clean

USER node

WORKDIR /home/node

COPY --chown=node:node . .

RUN rm -rf node_modules && npm install

CMD npm run test && node bin/ijsinstall.js
